baseURL = "https://theutz.com/"
title = 'theutz.com'
defaultContentLanguage = "en"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[languages]
  [languages.en]
    disabled = false
    languageCode = "en-US"
    languageDirection = "ltr"
    languageName = "English"
    title = 'theutz.com'
    weight = 1
    contentDir = "content/en"
  [languages.tr]
    disabled = false
    languageCode = "tr-TR"
    languageDirection = "ltr"
    languageName = "Türkçe"
    title = 'theutz.com'
    weight = 2
    contentDir = "content/tr"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
